apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: canberkerkmen/frontend:v4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: frontend
  ports:
    - name: lb-port
      port: 8080
      targetPort: 8080
  type: LoadBalancer
