apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        image: canberkerkmen/trial:v5
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
  labels:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: trial
  ports:
    - name: lb-port
      port: 8082
      targetPort: 8080
  type: LoadBalancer
